// jev-web — public API (typed decisions in the browser).
export { createDecider } from "./session.mjs";
export {
  registerDecisionFamily, createDecisionRuntime,
  listDecisionFamilies, getDecisionFamily,
} from "./registry.mjs";
export { normalizeQuestions, QUESTION_TYPES, NOUL_OPTIONS } from "./questions.mjs";
export { buildDecisionInput, typedMarkerIds, DecisionInputTooLongError } from "./encode.mjs";
export { answersFromScores, softmaxWithTemperature } from "./answers.mjs";
export {
  createLayaDecider,
  buildLayaSequence,
  collateLayaItems,
  layaAnswersFromLogits,
  layaTokenizerAdapter,
  renderLayaOptions,
  layaTempBucket,
  clampTemperature,
  LAYA_DEFAULT_MODEL,
  LAYA_DEFAULT_REVISION,
  LAYA_DEFAULT_SUBFOLDER,
  LAYA_DEFAULT_TEMPERATURES,
  LAYA_DEFAULT_TEMPERATURES_BY_OPTIONS,
  LAYA_DEFAULT_MAX_LEN,
  LAYA_DEFAULT_HEAD_MAX_LEN,
  LAYA_DEFAULT_MAX_PREFIXES,
  LAYA_QTYPE,
  LAYA_TEMP_MIN,
  LAYA_TEMP_MAX,
} from "./laya.mjs";
export {
  createStrandsDecider,
  renderStrandsQuestion,
  renderStrandsState,
  renderStrandsContent,
  buildStrandsBatch,
  collateStrandsItems,
  strandsOptionTokenIndices,
  strandsAnswersFromLogits,
  strandsChoiceConfidence,
  strandsScoreConfidence,
  STRANDS_DEFAULT_MODEL,
  STRANDS_DEFAULT_REVISION,
  STRANDS_DEFAULT_FILE,
  STRANDS_TEMPERATURE,
  STRANDS_TEMPERATURE_BY_KIND,
  STRANDS_ORDINAL_SMOOTHING,
  STRANDS_DEFAULT_MAX_LEN,
  STRANDS_MAX_QUESTION_FRACTION,
  STRANDS_KIND,
} from "./strands.mjs";
export {
  createBekkoDecider,
  renderBekkoContent,
  renderBekkoRequest,
  tokenizeBekkoRequest,
  collateBekkoDocs,
  bekkoSoftmax,
  bekkoAnswerFromLogits,
  BEKKO_DEFAULT_MODEL,
  BEKKO_DEFAULT_REVISION,
  BEKKO_DEFAULT_SUBDIR,
  BEKKO_68M_MODEL,
  BEKKO_68M_REVISION,
  BEKKO_400M_MODEL,
  BEKKO_400M_REVISION,
  BEKKO_VARIANTS,
  BEKKO_ATTENTION_BUDGET,
  BEKKO_DEFAULT_YES,
  BEKKO_DEFAULT_NO,
  BEKKO_NOUL_DESCRIPTIONS,
} from "./bekko.mjs";
export {
  createDecision2Decider,
  renderDecision2Content,
  renderDecision2Options,
  buildDecision2Segments,
  tokenizeDecision2Segments,
  decision2Softmax,
  decision2AnswerFromLogits,
  DECISION2_DEFAULT_MODEL,
  DECISION2_DEFAULT_REVISION,
  DECISION2_DEFAULT_FILE,
  DECISION2_EOS_MODEL,
  DECISION2_EOS_REVISION,
  DECISION2_SOL_MODEL,
  DECISION2_SOL_REVISION,
  DECISION2_VARIANTS,
  DECISION2_MAX_INPUT_TOKENS,
  DECISION2_NOUL_DESCRIPTIONS,
} from "./decision2.mjs";
export {
  createKevDecider,
  escapeKevText,
  packKevSequence,
  KEV_DEFAULT_MODEL,
  KEV_DEFAULT_REVISION,
  KEV_4B_MODEL,
  KEV_4B_REVISION,
  KEV_VARIANTS,
} from "./kev.mjs";
export {
  DEFAULT_MODEL,
  DEFAULT_REVISION,
  DEFAULT_TEMPERATURE,
  DEFAULT_MARKERS,
  DEFAULT_MAX_STATE_TOKENS,
  DEFAULT_MAX_LEN,
  resolveDevice,
  resolveDtype,
  detectWebGPU,
  loadModelConfig,
} from "./config.mjs";